<?php

namespace Tests\Unit;

use App\Services\MatchService;
use Tests\TestCase;

class MatchServiceTest extends TestCase
{
    public $matchService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->matchService = new MatchService();
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testGetAllTeams()
    {
        $result = $this->matchService->getAllTeams();
        $this->assertTrue($this->count($result)>0);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testGetTotalWeeks()
    {
        $result = $this->matchService->getTotalWeeks();
        $this->assertTrue($result>0);
    }
}
